blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<post_id>',post_detail, name='post_detail')
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views as portfolio_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', portfolio_views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #parte importante para poder ver las imagenes

blog/models.py
from django.db import models
import datetime
# Create your models here.

class Posts(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

#python manage.py createsuper user se usa para el usuario admin
# recuerda hacer las migraciones
# Create your models here.
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/') #requiere instalar pillow
    url = URLField(blank=True)

# primero aca luego a admin

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Posts

# Create your views here.
def render_posts(request):
    posts = Posts.objects.all()

    return render(request, 'post.html', {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html', {'projects': projects})

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    <h1>post</h1>


    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body">
                <div class="row">
                    <div class="col-3">
                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                    </div>
                    <div class="col-9">
                        <h3>{{ post.title }}</h3>
                        <p>{{ post.description|striptags|truncatechars:100}}</p>
                        <h4>{{ post.date| date:'M d Y' }}</h4>
                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{ post.title }}</a> 
                        <!-- esto es para enviar a un url especifico con el nombre declarado en las urls -->
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
    
{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <h3>{{ post.title }}</h3>
        <h4 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h4>
        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
        <div class="my-4">
            <p>{{ post.description|safe }}</p>
        </div>
    </div>

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
    <h2>home</h2>
    <div class="row my-4 text-center">
        {% for project in projects %}
            <div class="col-md-4 p-4 ">
                <div class="card bg-light card-project">
                    <div class="card-body">
                        <img src="{{ project.image.url}}" alt="{{ project.title}}" class="card-img-top">
                        <h3>{{ project.title }}</h3>
                        <p>{{ project.description }}</p>
                        {% if project.url %}
                            <a href="{{project.url}}" class="btn btn-light rouded-0 btn-sm" target="_blank">{{ project.url }}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    

{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django portfolio</title>
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Carlos Reyes</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/Carlos_Andres_Reyes_Peña_cv.pdf' %}" target="_blank">Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>